//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chadsoft.CTools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceSet {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceSet() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chadsoft.CTools.Properties.ResourceSet", typeof(ResourceSet).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The core CTools library..
        /// </summary>
        internal static string AssemblyDescription {
            get {
                return ResourceManager.GetString("AssemblyDescription", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap AssemblyImage {
            get {
                object obj = ResourceManager.GetObject("AssemblyImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A hex editor..
        /// </summary>
        internal static string EditorDescriptionBinary {
            get {
                return ResourceManager.GetString("EditorDescriptionBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex editor.
        /// </summary>
        internal static string EditorNameBinary {
            get {
                return ResourceManager.GetString("EditorNameBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A blank completely empty file..
        /// </summary>
        internal static string FileDescriptionEmpty {
            get {
                return ResourceManager.GetString("FileDescriptionEmpty", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FileImageEmpty {
            get {
                object obj = ResourceManager.GetObject("FileImageEmpty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty File.
        /// </summary>
        internal static string FileNameEmpty {
            get {
                return ResourceManager.GetString("FileNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation files.
        /// </summary>
        internal static string FormatCategoryAnimations {
            get {
                return ResourceManager.GetString("FormatCategoryAnimations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data files.
        /// </summary>
        internal static string FormatCategoryData {
            get {
                return ResourceManager.GetString("FormatCategoryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect files.
        /// </summary>
        internal static string FormatCategoryEffects {
            get {
                return ResourceManager.GetString("FormatCategoryEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font files.
        /// </summary>
        internal static string FormatCategoryFonts {
            get {
                return ResourceManager.GetString("FormatCategoryFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files.
        /// </summary>
        internal static string FormatCategoryImages {
            get {
                return ResourceManager.GetString("FormatCategoryImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout files.
        /// </summary>
        internal static string FormatCategoryLayouts {
            get {
                return ResourceManager.GetString("FormatCategoryLayouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting files.
        /// </summary>
        internal static string FormatCategoryLighting {
            get {
                return ResourceManager.GetString("FormatCategoryLighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model files.
        /// </summary>
        internal static string FormatCategoryModels {
            get {
                return ResourceManager.GetString("FormatCategoryModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music files.
        /// </summary>
        internal static string FormatCategoryMusic {
            get {
                return ResourceManager.GetString("FormatCategoryMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video files.
        /// </summary>
        internal static string FormatCategoryVideo {
            get {
                return ResourceManager.GetString("FormatCategoryVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary data file..
        /// </summary>
        internal static string FormatDescriptionBinary {
            get {
                return ResourceManager.GetString("FormatDescriptionBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .blight lighting file..
        /// </summary>
        internal static string FormatDescriptionBlight {
            get {
                return ResourceManager.GetString("FormatDescriptionBlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .blmap lighting file..
        /// </summary>
        internal static string FormatDescriptionBlmap {
            get {
                return ResourceManager.GetString("FormatDescriptionBlmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .bmg text file.
        /// </summary>
        internal static string FormatDescriptionBmg {
            get {
                return ResourceManager.GetString("FormatDescriptionBmg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .brasd object animation file..
        /// </summary>
        internal static string FormatDescriptionBrasd {
            get {
                return ResourceManager.GetString("FormatDescriptionBrasd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .brctr control file..
        /// </summary>
        internal static string FormatDescriptionBrctr {
            get {
                return ResourceManager.GetString("FormatDescriptionBrctr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .breff effect information file..
        /// </summary>
        internal static string FormatDescriptionBreff {
            get {
                return ResourceManager.GetString("FormatDescriptionBreff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .breft effect image file..
        /// </summary>
        internal static string FormatDescriptionBreft {
            get {
                return ResourceManager.GetString("FormatDescriptionBreft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .brfnt font file..
        /// </summary>
        internal static string FormatDescriptionBrfnt {
            get {
                return ResourceManager.GetString("FormatDescriptionBrfnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .brlan animation file..
        /// </summary>
        internal static string FormatDescriptionBrlan {
            get {
                return ResourceManager.GetString("FormatDescriptionBrlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .brlyt layout file..
        /// </summary>
        internal static string FormatDescriptionBrlyt {
            get {
                return ResourceManager.GetString("FormatDescriptionBrlyt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .brres model file..
        /// </summary>
        internal static string FormatDescriptionBrres {
            get {
                return ResourceManager.GetString("FormatDescriptionBrres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .brstm music file.
        /// </summary>
        internal static string FormatDescriptionBrstm {
            get {
                return ResourceManager.GetString("FormatDescriptionBrstm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .bti image file..
        /// </summary>
        internal static string FormatDescriptionBti {
            get {
                return ResourceManager.GetString("FormatDescriptionBti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .bwav music file.
        /// </summary>
        internal static string FormatDescriptionBwav {
            get {
                return ResourceManager.GetString("FormatDescriptionBwav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .csv data file..
        /// </summary>
        internal static string FormatDescriptionCsv {
            get {
                return ResourceManager.GetString("FormatDescriptionCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .kcl collision information file..
        /// </summary>
        internal static string FormatDescriptionKcl {
            get {
                return ResourceManager.GetString("FormatDescriptionKcl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .kmp course information file..
        /// </summary>
        internal static string FormatDescriptionKmp {
            get {
                return ResourceManager.GetString("FormatDescriptionKmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mid music file.
        /// </summary>
        internal static string FormatDescriptionMid {
            get {
                return ResourceManager.GetString("FormatDescriptionMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .rsca camera animation file..
        /// </summary>
        internal static string FormatDescriptionRsca {
            get {
                return ResourceManager.GetString("FormatDescriptionRsca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .thp video file..
        /// </summary>
        internal static string FormatDescriptionThp {
            get {
                return ResourceManager.GetString("FormatDescriptionThp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .tpl image file..
        /// </summary>
        internal static string FormatDescriptionTpl {
            get {
                return ResourceManager.GetString("FormatDescriptionTpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .txt text file..
        /// </summary>
        internal static string FormatDescriptionTxt {
            get {
                return ResourceManager.GetString("FormatDescriptionTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown data file..
        /// </summary>
        internal static string FormatDescriptionUnknown {
            get {
                return ResourceManager.GetString("FormatDescriptionUnknown", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FormatImageBinary {
            get {
                object obj = ResourceManager.GetObject("FormatImageBinary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormatImageBlight {
            get {
                object obj = ResourceManager.GetObject("FormatImageBlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormatImageBlmap {
            get {
                object obj = ResourceManager.GetObject("FormatImageBlmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormatImageBmg {
            get {
                object obj = ResourceManager.GetObject("FormatImageBmg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormatImageBrasd {
            get {
                object obj = ResourceManager.GetObject("FormatImageBrasd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormatImageBrctr {
            get {
                object obj = ResourceManager.GetObject("FormatImageBrctr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormatImageBreff {
            get {
                object obj = ResourceManager.GetObject("FormatImageBreff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormatImageBreft {
            get {
                object obj = ResourceManager.GetObject("FormatImageBreft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormatImageBrfnt {
            get {
                object obj = ResourceManager.GetObject("FormatImageBrfnt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormatImageBrlan {
            get {
                object obj = ResourceManager.GetObject("FormatImageBrlan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormatImageBrlyt {
            get {
                object obj = ResourceManager.GetObject("FormatImageBrlyt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormatImageBrres {
            get {
                object obj = ResourceManager.GetObject("FormatImageBrres", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormatImageBti {
            get {
                object obj = ResourceManager.GetObject("FormatImageBti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormatImageKcl {
            get {
                object obj = ResourceManager.GetObject("FormatImageKcl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormatImageKmp {
            get {
                object obj = ResourceManager.GetObject("FormatImageKmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormatImageRsca {
            get {
                object obj = ResourceManager.GetObject("FormatImageRsca", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormatImageSound {
            get {
                object obj = ResourceManager.GetObject("FormatImageSound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormatImageThp {
            get {
                object obj = ResourceManager.GetObject("FormatImageThp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormatImageTpl {
            get {
                object obj = ResourceManager.GetObject("FormatImageTpl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormatImageUnknown {
            get {
                object obj = ResourceManager.GetObject("FormatImageUnknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary file.
        /// </summary>
        internal static string FormatNameBinary {
            get {
                return ResourceManager.GetString("FormatNameBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting file.
        /// </summary>
        internal static string FormatNameBlight {
            get {
                return ResourceManager.GetString("FormatNameBlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting file.
        /// </summary>
        internal static string FormatNameBlmap {
            get {
                return ResourceManager.GetString("FormatNameBlmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text file.
        /// </summary>
        internal static string FormatNameBmg {
            get {
                return ResourceManager.GetString("FormatNameBmg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object animation file.
        /// </summary>
        internal static string FormatNameBrasd {
            get {
                return ResourceManager.GetString("FormatNameBrasd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control file.
        /// </summary>
        internal static string FormatNameBrctr {
            get {
                return ResourceManager.GetString("FormatNameBrctr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect information file.
        /// </summary>
        internal static string FormatNameBreff {
            get {
                return ResourceManager.GetString("FormatNameBreff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect image file.
        /// </summary>
        internal static string FormatNameBreft {
            get {
                return ResourceManager.GetString("FormatNameBreft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font file.
        /// </summary>
        internal static string FormatNameBrfnt {
            get {
                return ResourceManager.GetString("FormatNameBrfnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation file.
        /// </summary>
        internal static string FormatNameBrlan {
            get {
                return ResourceManager.GetString("FormatNameBrlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout file.
        /// </summary>
        internal static string FormatNameBrlyt {
            get {
                return ResourceManager.GetString("FormatNameBrlyt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model file.
        /// </summary>
        internal static string FormatNameBrres {
            get {
                return ResourceManager.GetString("FormatNameBrres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music file.
        /// </summary>
        internal static string FormatNameBrstm {
            get {
                return ResourceManager.GetString("FormatNameBrstm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file.
        /// </summary>
        internal static string FormatNameBti {
            get {
                return ResourceManager.GetString("FormatNameBti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music file.
        /// </summary>
        internal static string FormatNameBwav {
            get {
                return ResourceManager.GetString("FormatNameBwav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data file.
        /// </summary>
        internal static string FormatNameCsv {
            get {
                return ResourceManager.GetString("FormatNameCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collision information file.
        /// </summary>
        internal static string FormatNameKcl {
            get {
                return ResourceManager.GetString("FormatNameKcl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course information file.
        /// </summary>
        internal static string FormatNameKmp {
            get {
                return ResourceManager.GetString("FormatNameKmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music file.
        /// </summary>
        internal static string FormatNameMid {
            get {
                return ResourceManager.GetString("FormatNameMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera animation file.
        /// </summary>
        internal static string FormatNameRsca {
            get {
                return ResourceManager.GetString("FormatNameRsca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video file.
        /// </summary>
        internal static string FormatNameThp {
            get {
                return ResourceManager.GetString("FormatNameThp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file.
        /// </summary>
        internal static string FormatNameTpl {
            get {
                return ResourceManager.GetString("FormatNameTpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text file.
        /// </summary>
        internal static string FormatNameTxt {
            get {
                return ResourceManager.GetString("FormatNameTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data file.
        /// </summary>
        internal static string FormatNameUnknown {
            get {
                return ResourceManager.GetString("FormatNameUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTools.
        /// </summary>
        internal static string MessageBoxTitle {
            get {
                return ResourceManager.GetString("MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update error
        ///{0}.
        /// </summary>
        internal static string MessageErrorUpdate {
            get {
                return ResourceManager.GetString("MessageErrorUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has changed since it was last saved.
        ///Do you wish to save the changes?.
        /// </summary>
        internal static string MessageFileClose {
            get {
                return ResourceManager.GetString("MessageFileClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available to version {0}.
        ///Do you wish to update now?.
        /// </summary>
        internal static string MessageUpdateAvailable {
            get {
                return ResourceManager.GetString("MessageUpdateAvailable", resourceCulture);
            }
        }
    }
}
